"""create vehicle history table

Revision ID: 9b690e90c096
Revises: fb7e17337039
Create Date: 2026-10-04 11:17:05.526778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b690e90c096'
down_revision: Union[str, Sequence[str], None] = 'fb7e17337039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(length=100), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('communication_status', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('boot_id', sa.String(length=100), nullable=True),
    sa.Column('gps_fix', sa.Boolean(), nullable=True),
    sa.Column('satellites', sa.Integer(), nullable=True),
    sa.Column('hdop', sa.Float(), nullable=True),
    sa.Column('gps_source', sa.String(length=50), nullable=True),
    sa.Column('transport', sa.String(length=50), nullable=True),
    sa.Column('convoy_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_history_boot_id'), 'vehicle_history', ['boot_id'], unique=False)
    op.create_index(op.f('ix_vehicle_history_convoy_id'), 'vehicle_history', ['convoy_id'], unique=False)
    op.create_index(op.f('ix_vehicle_history_device_id'), 'vehicle_history', ['device_id'], unique=False)
    op.create_index(op.f('ix_vehicle_history_recorded_at'), 'vehicle_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_vehicle_history_sequence_number'), 'vehicle_history', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_vehicle_history_timestamp'), 'vehicle_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vehicle_history_vehicle_id'), 'vehicle_history', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_history_vehicle_id'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_timestamp'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_sequence_number'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_recorded_at'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_device_id'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_convoy_id'), table_name='vehicle_history')
    op.drop_index(op.f('ix_vehicle_history_boot_id'), table_name='vehicle_history')
    op.drop_table('vehicle_history')
    # ### end Alembic commands ###
