"""create vehicle sessions table

Revision ID: d832ee5b1cc7
Revises: 6d671058e7d1
Create Date: 2026-10-04 09:13:32.100807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd832ee5b1cc7'
down_revision: Union[str, Sequence[str], None] = '6d671058e7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(length=100), nullable=False),
    sa.Column('boot_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_sessions_boot_id'), 'vehicle_sessions', ['boot_id'], unique=False)
    op.create_index(op.f('ix_vehicle_sessions_vehicle_id'), 'vehicle_sessions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_sessions_vehicle_id'), table_name='vehicle_sessions')
    op.drop_index(op.f('ix_vehicle_sessions_boot_id'), table_name='vehicle_sessions')
    op.drop_table('vehicle_sessions')
    # ### end Alembic commands ###
