"""create convoy journey and route tables

Revision ID: 2e93dd02cb69
Revises: 9b690e90c096
Create Date: 2026-10-04 11:39:40.669346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e93dd02cb69'
down_revision: Union[str, Sequence[str], None] = '9b690e90c096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convoy_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('convoy_id', sa.String(length=100), nullable=False),
    sa.Column('vehicle_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convoy_members_convoy_id'), 'convoy_members', ['convoy_id'], unique=False)
    op.create_index(op.f('ix_convoy_members_vehicle_id'), 'convoy_members', ['vehicle_id'], unique=False)
    op.create_table('convoys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('convoy_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('leader_vehicle_id', sa.String(length=100), nullable=True),
    sa.Column('journey_id', sa.String(length=100), nullable=True),
    sa.Column('route_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convoys_convoy_id'), 'convoys', ['convoy_id'], unique=True)
    op.create_index(op.f('ix_convoys_journey_id'), 'convoys', ['journey_id'], unique=False)
    op.create_index(op.f('ix_convoys_leader_vehicle_id'), 'convoys', ['leader_vehicle_id'], unique=False)
    op.create_index(op.f('ix_convoys_route_id'), 'convoys', ['route_id'], unique=False)
    op.create_table('journeys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journey_id', sa.String(length=100), nullable=False),
    sa.Column('convoy_id', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=500), nullable=False),
    sa.Column('destination', sa.String(length=500), nullable=False),
    sa.Column('route_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journeys_convoy_id'), 'journeys', ['convoy_id'], unique=False)
    op.create_index(op.f('ix_journeys_created_by'), 'journeys', ['created_by'], unique=False)
    op.create_index(op.f('ix_journeys_journey_id'), 'journeys', ['journey_id'], unique=True)
    op.create_index(op.f('ix_journeys_route_id'), 'journeys', ['route_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=500), nullable=False),
    sa.Column('destination', sa.String(length=500), nullable=False),
    sa.Column('geometry', sa.Text(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_created_by'), 'routes', ['created_by'], unique=False)
    op.create_index(op.f('ix_routes_route_id'), 'routes', ['route_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_route_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_created_by'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_journeys_route_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_journey_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_created_by'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_convoy_id'), table_name='journeys')
    op.drop_table('journeys')
    op.drop_index(op.f('ix_convoys_route_id'), table_name='convoys')
    op.drop_index(op.f('ix_convoys_leader_vehicle_id'), table_name='convoys')
    op.drop_index(op.f('ix_convoys_journey_id'), table_name='convoys')
    op.drop_index(op.f('ix_convoys_convoy_id'), table_name='convoys')
    op.drop_table('convoys')
    op.drop_index(op.f('ix_convoy_members_vehicle_id'), table_name='convoy_members')
    op.drop_index(op.f('ix_convoy_members_convoy_id'), table_name='convoy_members')
    op.drop_table('convoy_members')
    # ### end Alembic commands ###
