"""create vehicles table

Revision ID: e83222d6e9f4
Revises: 649bb2cb8e5d
Create Date: 2026-10-04 02:15:55.021766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83222d6e9f4'
down_revision: Union[str, Sequence[str], None] = '649bb2cb8e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_device_id'), 'vehicles', ['device_id'], unique=True)
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_device_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
